version: "3.9"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  local-dev-consul:
    image: "consul"
    container_name: "local-dev-consul"
    networks:
      - local-dev-network
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0

networks:
  local-dev-network:
    name: "local-dev-network"
    driver: bridge

volumes: 
  mongodata: